name: 'Test multi-platform Docker images'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  test-on-linux-x86:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/developmententity/aws-cloud-tools:initial
      options:
        -v /dev:/dev

    steps:
      - name: 'Docker image test (amd64)'
        run: |
          sudo mkdir .ansible && sudo chown -R a+rw .ansible
          ansible --version | awk -F"core " '/core/{print "v"$2}' | sed 's/]//'
          aws --version | awk -F' ' '{print $1}' | awk -F'/' '{print $2}'
          sam --version | awk '{print "v"$NF}'
          helm version --short | awk -F'+' '{print $1}'
          k9s version | awk '/Version:/ {print $2}'
          kops version | awk -F'git-' 'NR==1 {print $2}' | sed 's/)//'
          kubectl version --client | awk -F': ' 'NR==1 {print $2}'
          terraform version | awk -F'v' 'NR==1 {print $2}'
          terragrunt --version | awk 'NR==1 {print $NF}'

  test-on-linux-arm:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/developmententity/aws-cloud-tools:initial
      options:
        -v /dev:/dev

    steps:
      - name: 'Docker image test (arm64)'
        run: |
          sudo mkdir .ansible && sudo chown -R a+rw .ansible
          ansible --version | awk -F"core " '/core/{print "v"$2}' | sed 's/]//'
          aws --version | awk -F' ' '{print $1}' | awk -F'/' '{print $2}'
          sam --version | awk '{print "v"$NF}'
          helm version --short | awk -F'+' '{print $1}'
          k9s version | awk '/Version:/ {print $2}'
          kops version | awk -F'git-' 'NR==1 {print $2}' | sed 's/)//'
          kubectl version --client | awk -F': ' 'NR==1 {print $2}'
          terraform version | awk -F'v' 'NR==1 {print $2}'
          terragrunt --version | awk 'NR==1 {print $NF}'
