name: 'Test standalone (amd64)'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Install required packages (amd64)'
        run: |
          sudo apt-get update && \
          sudo apt-get -y --no-install-recommends install ca-certificates curl unzip && \
          sudo apt-get clean && sudo rm -rf "/var/lib/apt/lists/*"
      - name: 'Perform standalone install (amd64)'
        run: |
          sudo ./standalone-install.sh
      - name: 'AWS cloud tools test (amd64)'
        run: |
          aws --version | head -n 1
          sam --version | head -n 1
          helm version | head -n 1
          kubectl version --client | head -n 1
          terraform version | head -n 1
          terragrunt --version | head -n 1
